create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  clerk_user_id text not null unique,
  email text,
  full_name text,
  current_phase text check (current_phase in ('menstrual', 'follicular', 'ovulation', 'luteal')),
  cycle_length integer default 28 check (cycle_length between 21 and 40),
  period_length integer default 5 check (period_length between 2 and 10),
  last_period_start date default current_date,
  is_premium boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  phase_key text check (phase_key in ('menstrual', 'follicular', 'ovulation', 'luteal')),
  phase_label text,
  calories integer default 0,
  time_minutes integer default 20,
  nutritional_insight text,
  image_url text,
  ingredients jsonb not null default '[]'::jsonb,
  instructions jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.saved_recipes (
  id uuid primary key default gen_random_uuid(),
  clerk_user_id text not null,
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique (clerk_user_id, recipe_id)
);

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text not null,
  image_url text,
  read_time text,
  tag text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.videos (
  id text primary key,
  phase_key text not null check (phase_key in ('menstrual', 'follicular', 'ovulation', 'luteal')),
  category text not null,
  title text not null,
  description text not null,
  youtube_url text,
  video_url text,
  duration text not null,
  thumbnail text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.daily_logs (
  id uuid primary key default gen_random_uuid(),
  clerk_user_id text not null,
  mood text,
  symptoms jsonb not null default '[]'::jsonb,
  notes text,
  cycle_day integer,
  phase_key text check (phase_key in ('menstrual', 'follicular', 'ovulation', 'luteal')),
  logged_at timestamptz not null default timezone('utc', now()),
  log_date date generated always as ((logged_at at time zone 'utc')::date) stored,
  created_at timestamptz not null default timezone('utc', now()),
  unique (clerk_user_id, log_date)
);

alter table public.profiles enable row level security;
alter table public.recipes enable row level security;
alter table public.saved_recipes enable row level security;
alter table public.articles enable row level security;
alter table public.videos enable row level security;
alter table public.daily_logs enable row level security;

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  clerk_user_id text not null references public.profiles(clerk_user_id) on delete cascade,
  stripe_customer_id text,
  stripe_subscription_id text,
  status text check (status in ('active', 'canceled', 'incomplete', 'past_due')),
  plan_type text check (plan_type in ('monthly', 'yearly')),
  current_period_end timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.subscriptions enable row level security;

create policy "Users can read own subscriptions"
on public.subscriptions for select
using (auth.jwt() ->> 'sub' = clerk_user_id);

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles
for select
using (auth.jwt() ->> 'sub' = clerk_user_id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles
for insert
with check (auth.jwt() ->> 'sub' = clerk_user_id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
using (auth.jwt() ->> 'sub' = clerk_user_id)
with check (auth.jwt() ->> 'sub' = clerk_user_id);

drop policy if exists "Anyone can read recipes" on public.recipes;
create policy "Anyone can read recipes"
on public.recipes
for select
using (true);

drop policy if exists "Users can read own saved recipes" on public.saved_recipes;
create policy "Users can read own saved recipes"
on public.saved_recipes
for select
using (auth.jwt() ->> 'sub' = clerk_user_id);

drop policy if exists "Users can insert own saved recipes" on public.saved_recipes;
create policy "Users can insert own saved recipes"
on public.saved_recipes
for insert
with check (auth.jwt() ->> 'sub' = clerk_user_id);

drop policy if exists "Users can delete own saved recipes" on public.saved_recipes;
create policy "Users can delete own saved recipes"
on public.saved_recipes
for delete
using (auth.jwt() ->> 'sub' = clerk_user_id);

drop policy if exists "Anyone can read articles" on public.articles;
create policy "Anyone can read articles"
on public.articles
for select
using (true);

drop policy if exists "Anyone can read videos" on public.videos;
create policy "Anyone can read videos"
on public.videos
for select
using (true);

drop policy if exists "Admins can manage videos" on public.videos;
create policy "Admins can manage videos"
on public.videos
for all
using (
  (auth.jwt() ->> 'role' = 'owner') or 
  (auth.jwt() ->> 'role' = 'admin') or
  (auth.jwt() ->> 'email' = 'salat.mahenoor7.8.6@gmail.com')
);

drop policy if exists "Users can read own daily logs" on public.daily_logs;
create policy "Users can read own daily logs"
on public.daily_logs
for select
using (auth.jwt() ->> 'sub' = clerk_user_id);

drop policy if exists "Users can insert own daily logs" on public.daily_logs;
create policy "Users can insert own daily logs"
on public.daily_logs
for insert
with check (auth.jwt() ->> 'sub' = clerk_user_id);

drop policy if exists "Users can update own daily logs" on public.daily_logs;
create policy "Users can update own daily logs"
on public.daily_logs
for update
using (auth.jwt() ->> 'sub' = clerk_user_id)
with check (auth.jwt() ->> 'sub' = clerk_user_id);

-- Storage bucket for video content
-- Note: Run these in the Supabase SQL Editor if they don't apply automatically
-- insert into storage.buckets (id, name, public) values ('video-content', 'video-content', true) on conflict (id) do nothing;

-- drop policy if exists "Public Access" on storage.objects;
-- create policy "Public Access" on storage.objects for select using ( bucket_id = 'video-content' );

-- drop policy if exists "Admins can upload videos" on storage.objects;
-- create policy "Admins can upload videos" on storage.objects for insert with check (
--   bucket_id = 'video-content' AND (
--     (auth.jwt() ->> 'role' = 'owner') OR
--     (auth.jwt() ->> 'role' = 'admin') OR
--     (auth.jwt() ->> 'email' = 'salat.mahenoor7.8.6@gmail.com')
--   )
-- );

-- Storage bucket for recipe images
-- insert into storage.buckets (id, name, public) values ('recipe-images', 'recipe-images', true) on conflict (id) do nothing;

-- drop policy if exists "Public Access" on storage.objects;
-- create policy "Public Access" on storage.objects for select using ( bucket_id = 'recipe-images' );

-- drop policy if exists "Admins can upload recipe images" on storage.objects;
-- create policy "Admins can upload recipe images" on storage.objects for insert with check (
--   bucket_id = 'recipe-images' AND (
--     (auth.jwt() ->> 'role' = 'owner') OR
--     (auth.jwt() ->> 'role' = 'admin') OR
--     (auth.jwt() ->> 'email' = 'salat.mahenoor7.8.6@gmail.com')
--   )
-- );
