export const MOCK_RECIPES = [
  {
    id: '1',
    title: 'Bowl de Quinoa y Espinaca',
    calories: 420,
    time: 25,
    category: 'Fase Menstrual',
    phaseKey: 'menstrual',
    mealType: 'lunch',
    nutritionalInsight:
      'El hierro de las espinacas y la quinoa ayuda a reponer tus niveles de energia naturales durante estos dias de renovacion.',
    image: { uri: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800' },
    ingredients: [
      '1 taza de quinoa cocida',
      '2 tazas de espinaca baby',
      '1/2 aguacate en rebanadas',
      '1/4 taza de garbanzos',
      'Semillas de sesamo',
      'Aderezo de limon y tahini',
    ],
    instructions: [
      'Lava y cocina la quinoa segun las instrucciones del paquete.',
      'En un bowl, coloca una base de espinacas frescas.',
      'Agrega la quinoa, el aguacate y los garbanzos.',
      'Espolvorea semillas de sesamo por encima.',
      'Bana con el aderezo de tahini antes de servir.',
    ],
  },
  {
    id: '2',
    title: 'Ensalada de pollo con quinoa tostada',
    calories: 320,
    time: 15,
    category: 'Fase Folicular',
    phaseKey: 'follicular',
    mealType: 'lunch',
    nutritionalInsight:
      'La proteina del pollo y los aminoacidos de la quinoa te daran la energia sostenida ideal para esta etapa ascendente de tu ciclo.',
    image: { uri: 'https://images.unsplash.com/photo-1505253758473-96b7015fcd40?w=800' },
    ingredients: [
      '1 pechuga de pollo asada en trozos',
      '1/2 taza de quinoa tostada',
      '2 tazas de espinaca fresca o kale',
      '1/2 aguacate rebanado',
      'Tomates cherry al gusto',
      'Aderezo ligero de limon y aceite de oliva',
    ],
    instructions: [
      'Tuesta la quinoa en una sarten a fuego medio hasta que este dorada.',
      'En un bowl amplio, mezcla la espinaca, el pollo, el tomate y el aguacate.',
      'Agrega la quinoa tostada encima para un toque crujiente.',
      'Bana con el aderezo ligero justo antes de comer para mantener la frescura.',
    ],
  },
  {
    id: '3',
    title: 'Salmon con Esparragos y Limon',
    calories: 540,
    time: 30,
    category: 'Fase Ovulacion',
    phaseKey: 'ovulation',
    mealType: 'dinner',
    nutritionalInsight:
      'El Omega-3 y el zinc del salmon son aliados clave para potenciar tu fertilidad y luminosidad natural en esta fase.',
    image: { uri: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800' },
    ingredients: [
      '200g de filete de salmon fresco',
      '1 manojo de esparragos tiernos',
      '2 cucharadas de aceite de oliva',
      'Rodajas de limon amarillo',
      'Sal de mar y pimienta negra',
    ],
    instructions: [
      'Precalienta el horno a 200C.',
      'Coloca el salmon y los esparragos en una bandeja para hornear.',
      'Rocia con aceite de oliva y sazona con sal y mucha pimienta.',
      'Coloca las rodajas de limon sobre el salmon.',
      'Hornea durante 12-15 minutos hasta que el salmon este cocido.',
    ],
  },
  {
    id: '4',
    title: 'Poke bowl de arroz con atun, mango y aguacate',
    calories: 450,
    time: 20,
    category: 'Fase Lutea',
    phaseKey: 'luteal',
    mealType: 'dinner',
    nutritionalInsight:
      'Las grasas saludables del aguacate y el atun, junto a la energia del arroz, promueven saciedad y balancean tus emociones antes de tu periodo.',
    image: { uri: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800' },
    ingredients: [
      '1 taza de arroz de sushi o integral',
      '150g de atun fresco en cubos',
      '1/2 mango maduro en cubos',
      '1/2 aguacate en rebanadas',
      'Edamames al gusto',
      'Salsa ponzu o soya baja en sodio',
      'Semillas de sesamo para decorar',
    ],
    instructions: [
      'Cocina el arroz de acuerdo a las instrucciones y colocarlo como base en tu bowl.',
      'Acomoda armonicamente el atun, mango, aguacate y edamames sobre el arroz.',
      'Vierte la salsa elegida de manera uniforme.',
      'Decora con semillas de sesamo y disfruta frio.',
    ],
  },
  {
    id: '5',
    title: 'Avena cremosa con cacao y nuez',
    calories: 380,
    time: 12,
    category: 'Fase Menstrual',
    phaseKey: 'menstrual',
    mealType: 'breakfast',
    nutritionalInsight:
      'La avena tibia, el cacao y la nuez ofrecen confort y saciedad suave para los dias menstruales.',
    image: { uri: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800' },
    ingredients: [
      '1 taza de avena',
      '2 tazas de leche o bebida vegetal',
      '1 cucharada de cacao puro',
      '1 cucharada de nuez picada',
      'Canela al gusto',
      '1 cucharadita de miel opcional',
    ],
    instructions: [
      'Calienta la leche en una olla pequena.',
      'Agrega la avena, el cacao y la canela.',
      'Cocina a fuego bajo hasta que espese.',
      'Sirve con nuez picada y miel si deseas.',
    ],
  },
  {
    id: '6',
    title: 'Crema de calabaza con jengibre y lentejas',
    calories: 360,
    time: 28,
    category: 'Fase Menstrual',
    phaseKey: 'menstrual',
    mealType: 'dinner',
    nutritionalInsight:
      'Esta crema aporta hierro, fibra y calor para acompanarte en la fase menstrual.',
    image: { uri: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800' },
    ingredients: [
      '2 tazas de calabaza en cubos',
      '1 taza de lentejas cocidas',
      '1 trozo pequeno de jengibre',
      '1 cebolla pequena',
      '1 cucharada de aceite de oliva',
      'Caldo de verduras',
      'Sal y pimienta',
    ],
    instructions: [
      'Sofrie la cebolla y el jengibre.',
      'Agrega la calabaza y el caldo.',
      'Cocina hasta que la calabaza ablande.',
      'Anade las lentejas y licua hasta obtener una crema suave.',
    ],
  },
  {
    id: '7',
    title: 'Tacos de pavo con col morada y pico de gallo',
    calories: 410,
    time: 20,
    category: 'Fase Folicular',
    phaseKey: 'follicular',
    mealType: 'dinner',
    nutritionalInsight:
      'Proteina magra y vegetales crujientes acompanian el aumento de energia de la fase folicular.',
    image: { uri: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=800' },
    ingredients: [
      '250g de pavo molido',
      '6 tortillas de maiz',
      '1 taza de col morada rallada',
      '1 tomate picado',
      '1/4 de cebolla morada',
      'Cilantro',
      'Limon',
      'Sal y comino',
    ],
    instructions: [
      'Cocina el pavo con sal y comino.',
      'Prepara el pico de gallo con tomate, cebolla y cilantro.',
      'Calienta las tortillas.',
      'Arma los tacos con col morada y termina con limon.',
    ],
  },
  {
    id: '8',
    title: 'Yogur griego con frutos rojos y semillas',
    calories: 290,
    time: 8,
    category: 'Fase Folicular',
    phaseKey: 'follicular',
    mealType: 'breakfast',
    nutritionalInsight:
      'El yogur griego y las berries hacen de este un desayuno ligero y rico en proteina.',
    image: { uri: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800' },
    ingredients: [
      '1 taza de yogur griego natural',
      '1/2 taza de frutos rojos',
      '1 cucharada de semillas de chía',
      '1 cucharada de granola',
      'Miel opcional',
    ],
    instructions: [
      'Sirve el yogur en un bowl.',
      'Anade frutos rojos y semillas.',
      'Corona con granola y un hilo de miel si lo deseas.',
    ],
  },
  {
    id: '9',
    title: 'Tostadas de hummus con huevo y rucula',
    calories: 430,
    time: 15,
    category: 'Fase Ovulacion',
    phaseKey: 'ovulation',
    mealType: 'breakfast',
    nutritionalInsight:
      'Huevos, hojas verdes y garbanzos ofrecen una comida equilibrada para la ovulacion.',
    image: { uri: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?w=800' },
    ingredients: [
      '2 rebanadas de pan integral',
      '1/2 taza de hummus',
      '2 huevos',
      '1 taza de rucula',
      'Aceite de oliva',
      'Sal, pimienta y paprika',
    ],
    instructions: [
      'Tuesta el pan hasta que quede crujiente.',
      'Unta una capa generosa de hummus.',
      'Coloca el huevo cocido o a la plancha encima.',
      'Agrega rucula y termina con aceite de oliva.',
    ],
  },
  {
    id: '10',
    title: 'Ensalada de camote, naranja y pepitas',
    calories: 390,
    time: 18,
    category: 'Fase Ovulacion',
    phaseKey: 'ovulation',
    mealType: 'lunch',
    nutritionalInsight:
      'La vitamina C de la naranja y los minerales de las pepitas hacen esta ensalada luminosa y fresca.',
    image: { uri: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800' },
    ingredients: [
      '1 camote mediano asado',
      '1 naranja en gajos',
      '2 tazas de espinaca',
      '2 cucharadas de pepitas',
      'Queso feta opcional',
      'Aderezo de aceite de oliva y limon',
    ],
    instructions: [
      'Asa el camote hasta que quede tierno.',
      'Mezcla espinaca, naranja y camote.',
      'Agrega pepitas y queso feta si deseas.',
      'Aliña con aceite de oliva y limon.',
    ],
  },
  {
    id: '11',
    title: 'Curry suave de garbanzos y coco',
    calories: 470,
    time: 30,
    category: 'Fase Lutea',
    phaseKey: 'luteal',
    mealType: 'dinner',
    nutritionalInsight:
      'Los carbohidratos reconfortantes y los garbanzos ayudan con los antojos de la fase lutea.',
    image: { uri: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800' },
    ingredients: [
      '1 taza de garbanzos cocidos',
      '1 taza de leche de coco',
      '1 cebolla pequena',
      '1 diente de ajo',
      '1 cucharadita de curry suave',
      '1 taza de arroz integral cocido',
      'Cilantro',
    ],
    instructions: [
      'Sofrie la cebolla y el ajo.',
      'Anade el curry y los garbanzos.',
      'Vierte la leche de coco y cocina 10 minutos.',
      'Sirve sobre arroz integral y decora con cilantro.',
    ],
  },
  {
    id: '12',
    title: 'Pasta integral con sardinas y espinacas',
    calories: 520,
    time: 22,
    category: 'Fase Lutea',
    phaseKey: 'luteal',
    mealType: 'dinner',
    nutritionalInsight:
      'Omega-3, fibra y carbohidratos completos sostienen la energia y la saciedad.',
    image: { uri: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800' },
    ingredients: [
      '200g de pasta integral',
      '1 lata de sardinas en aceite de oliva',
      '2 tazas de espinaca',
      '1 diente de ajo',
      'Limon',
      'Pimienta negra',
    ],
    instructions: [
      'Cocina la pasta al dente.',
      'Saltea el ajo con la espinaca.',
      'Agrega las sardinas y un poco de limon.',
      'Mezcla con la pasta and termina con pimienta.',
    ],
  },
  {
    id: '13',
    title: 'Mix de nueces y chocolate oscuro',
    calories: 180,
    time: 5,
    category: 'Fase Lutea',
    phaseKey: 'luteal',
    mealType: 'snack',
    nutritionalInsight:
      'El magnesio del cacao ayuda a reducir la tension premenstrual.',
    image: { uri: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800' },
    ingredients: [
      '30g de nueces mixtas',
      '2 cuadritos de chocolate oscuro 70%+',
    ],
    instructions: [
      'Mezcla las nueces and el chocolate en un tazon pequeno.',
    ],
  },
  {
    id: '14',
    title: 'Batido verde energizante',
    calories: 210,
    time: 10,
    category: 'Fase Folicular',
    phaseKey: 'follicular',
    mealType: 'snack',
    nutritionalInsight:
      'Ideal para media manana durante tu fase de mayor creatividad.',
    image: { uri: 'https://images.unsplash.com/photo-1544145945-f904253d0c71?w=800' },
    ingredients: [
      '1 taza de espinaca',
      '1/2 platano',
      '1/2 taza de pia',
      'Agua de coco',
    ],
    instructions: [
      'Licua todos los ingredientes hasta que este suave.',
    ],
  },
];

export const CURRENT_PHASE = {
  name: 'Folicular',
  day: 8,
  message:
    'Tu estrogeno esta subiendo. Es el momento perfecto para enfocarte en carbohidratos complejos y alimentos ricos en vitamina E.',
};

export const PHASES_DATA = {
  menstrual: {
    name: 'Menstrual',
    color: '#A78BFA',
    focus: 'Hierro & Vitamina C',
    advice: 'Prioriza alimentos calientes y nutritivos para mejorar el flujo y la energia.',
  },
  follicular: {
    name: 'Folicular',
    color: '#A3B3A5',
    focus: 'Probioticos & Fiber',
    advice: 'Excelente momento para alimentos fermentados que ayuden a metabolizar el estrogeno.',
  },
  ovulation: {
    name: 'Ovulacion',
    color: '#7BC8B8',
    focus: 'Antioxidantes',
    advice: 'Consume vegetales de hoja verde y frutas ricas en zinc para apoyar la fertilidad.',
  },
  luteal: {
    name: 'Lutea',
    color: '#8B5CF6',
    focus: 'Magnesio & Vitamina B6',
    advice: 'Opta por carbohidratos complejos para estabilizar el azucar en sangre y el animo.',
  },
};
