create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text not null,
  image_url text,
  read_time text,
  tag text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.videos (
  id text primary key,
  phase_key text not null check (phase_key in ('menstrual', 'follicular', 'ovulation', 'luteal')),
  category text not null,
  title text not null,
  description text not null,
  youtube_url text not null,
  duration text not null,
  thumbnail text,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.articles enable row level security;
alter table public.videos enable row level security;

drop policy if exists "Anyone can read articles" on public.articles;
create policy "Anyone can read articles"
on public.articles
for select
using (true);

drop policy if exists "Anyone can read videos" on public.videos;
create policy "Anyone can read videos"
on public.videos
for select
using (true);

insert into public.articles (id, title, excerpt, image_url, read_time, tag)
values
  (
    1,
    'Nutricion en la Fase Menstrual',
    'Consigue el alivio que necesitas con alimentos ricos en hierro y magnesio...',
    'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
    '5 min lectura',
    'NUTRICION'
  ),
  (
    2,
    'Yoga para el Alivio de Calambres',
    'Posturas suaves disenadas para reducir la inflamacion y el dolor...',
    'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    '8 min lectura',
    'BIENESTAR'
  ),
  (
    3,
    'Bio-Sincronizacion Avanzada',
    'Como optimizar tu productividad semanal segun tus niveles hormonales...',
    'https://images.unsplash.com/photo-1555244162-803834f70033?w=800',
    '10 min lectura',
    'ESTILO DE VIDA'
  )
on conflict (id) do update
set
  title = excluded.title,
  excerpt = excluded.excerpt,
  image_url = excluded.image_url,
  read_time = excluded.read_time,
  tag = excluded.tag;

select setval(
  pg_get_serial_sequence('public.articles', 'id'),
  coalesce((select max(id) from public.articles), 1),
  true
);

insert into public.videos (
  id,
  phase_key,
  category,
  title,
  description,
  youtube_url,
  duration,
  thumbnail
)
values
  (
    'video-follicular-1',
    'follicular',
    'Fase folicular',
    'Receta corta para fase folicular',
    'Una idea rapida para acompanar la etapa de energia ascendente con ingredientes frescos y saciantes.',
    'https://youtube.com/shorts/GdTEDblpPxY?feature=share',
    '0:56',
    'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800'
  ),
  (
    'video-cycle-1',
    'luteal',
    'Ciclo y nutricion',
    'Como conectar tu fase con tus comidas',
    'Explica de forma simple por que las recomendaciones cambian segun el momento de tu ciclo.',
    'https://youtube.com/shorts/Shg1SZKzZzw?feature=share',
    '1:12',
    'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800'
  ),
  (
    'video-menstrual-1',
    'menstrual',
    'Bienestar menstrual',
    'Pausa suave para dias menstruales',
    'Una propuesta de respiracion y descanso para acompanar la menstruacion con mas calma y confort.',
    'https://www.youtube.com/watch?v=B4kNiCwtl7M',
    '3:45',
    'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800'
  ),
  (
    'video-ovulation-1',
    'ovulation',
    'Fertilidad y energia',
    'Movimiento consciente para ovulacion',
    'Contenido pensado para los dias de mayor vitalidad, con foco en energia, ligereza y equilibrio.',
    'https://www.youtube.com/watch?v=inpok4MKVLM',
    '5:04',
    'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800'
  )
on conflict (id) do update
set
  phase_key = excluded.phase_key,
  category = excluded.category,
  title = excluded.title,
  description = excluded.description,
  youtube_url = excluded.youtube_url,
  duration = excluded.duration,
  thumbnail = excluded.thumbnail;
