-- Documents the public.key_foods table, which has real production data
-- (20+ rows per cycle phase, used by src/services/keyFoodsService.js) but
-- had NO CREATE TABLE statement anywhere in version control — it was built
-- by hand in the Supabase Table Editor. Uses IF NOT EXISTS / ADD COLUMN IF
-- NOT EXISTS throughout so this is a no-op against columns that already
-- exist on the live table; the one real change is enabling RLS with
-- explicit policies, matching the recipes/articles/videos pattern.
--
-- Verify after applying: confirm loadKeyFoods() in keyFoodsService.js still
-- returns data for regular (non-admin) users — if RLS was previously
-- disabled on this table, this is the first time access control applies.

create table if not exists public.key_foods (
  id bigint generated by default as identity primary key,
  phase_key text not null check (phase_key in ('menstrual', 'follicular', 'ovulation', 'luteal')),
  category_key text not null check (category_key in ('proteins', 'fats', 'carbs', 'veg_fruits')),
  name text not null,
  hormone_tag text default 'energy',
  meal_type text default 'lunch',
  image_url text,
  benefits text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.key_foods enable row level security;

drop policy if exists "Anyone can read key foods" on public.key_foods;
create policy "Anyone can read key foods"
on public.key_foods
for select
using (true);

drop policy if exists "Admins can manage key foods" on public.key_foods;
create policy "Admins can manage key foods"
on public.key_foods
for all
using (
  (auth.jwt() ->> 'role' = 'owner') or
  (auth.jwt() ->> 'role' = 'admin') or
  (auth.jwt() ->> 'email' = 'salat.mahenoor7.8.6@gmail.com')
)
with check (
  (auth.jwt() ->> 'role' = 'owner') or
  (auth.jwt() ->> 'role' = 'admin') or
  (auth.jwt() ->> 'email' = 'salat.mahenoor7.8.6@gmail.com')
);
